name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "Logging into Docker Hub..."
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t rosstafarian/flora-api .

      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing image to Docker Hub..."
          docker push rosstafarian/flora-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          echo "Installing AWS CLI..."
          sudo apt-get update
          sudo apt-get install -y curl awscli
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          echo "Configuring AWS CLI..."
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION
          aws configure set region $AWS_DEFAULT_REGION
          cat ~/.aws/credentials

      - name: Deploy to AWS Lightsail Containers
        run: |
          echo "Releasing to Amazon Lightsail..."
          aws lightsail create-container-service-deployment \
            --service-name flora-api \
            --containers '{
              "flora-api": {
                "image": "rosstafarian/flora-api:latest",
                "environment": {
                  "ENVIRONMENT": "${{ secrets.ENVIRONMENT }}",
                  "MONGODB_URI": "${{ secrets.MONGODB_URI }}",
                  "DB_NAME": "${{ secrets.DB_NAME }}",
                  "LOKI_URL": "${{ secrets.LOKI_URL }}"
                },
                "ports": {
                  "8080": "HTTP"
                }
              }
            }' \
            --public-endpoint '{
              "containerName": "flora-api",
              "containerPort": 8080,
              "healthCheck": {
                "path": "/ping",
                "intervalSeconds": 300
              }
            }'
